### ISSUE TITLE
Default config for Gossip strategy fails in 3.3.2

### ISSUE THREAD

**Issue by drewble** [bitwalker/libcluster#189] opened 2023-02-23 18:33 UTC
### Steps to reproduce

- Configuration Used

In a Phoenix 1.6 and a Phoenix 1.7rc app using Elixir 1.14:

```elixir
# config.exs
config :libcluster,
  topologies: [
    gossip: [
      strategy: Elixir.Cluster.Strategy.Gossip,
      config: [
        port: 45892,
        if_addr: "127.0.0.1",
        multicast_if: "192.168.1.1",
        multicast_addr: "233.252.1.32",
        secret: "somepassword"
      ]
    ]
  ]

#application.ex
{Cluster.Supervisor, [Application.get_env(:libcluster, :topologies), [name: MyApp.ClusterSupervisor]]},
```

- Strategy Used

Gossip

- Errors/Incorrect Behaviour Encountered

```
** (Mix) Could not start application my_app: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: Cluster.Supervisor
    ** (EXIT) shutdown: failed to start child: :gossip
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, :einval}
                (libcluster 3.3.2) lib/strategy/gossip.ex:127: Cluster.Strategy.Gossip.init/1
                (stdlib 4.1) gen_server.erl:851: :gen_server.init_it/2
                (stdlib 4.1) gen_server.erl:814: :gen_server.init_it/6
                (stdlib 4.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

### Description of issue

- What are the expected results?

Expect application to start with default Gossip strategy config. Default configuration succeeds in v3.3.1

- Is the documentation incorrect?

Documentation seems to be correct

**Comment by kebling** [comment] 2023-03-04 02:39
@drewble I was getting a similar error when using `strategy: Cluster.Strategy.LocalEpmd`.

It turns out the `epmd` daemon wasn't running on my system because I had rebooted, and it apparently only starts if you pass `--name` while starting the app.

In my case, running `iex --name node-0 -S mix phx.server` started the `epmd` daemon. It will continue to run after exiting the app with ctrl-c.

**Comment by bitwalker** [comment] 2023-06-22 17:59
I'll add a note to the docs for this strategy to mention that @kebling, thanks!

**Comment by bitwalker** [comment] 2023-06-22 18:01
Actually, I think this is a separate issue, but my suspicion is that it has to do with the multicast configuration used. I'll see if I can reproduce

**Comment by bitwalker** [comment] 2023-06-22 18:41
I'm not able to reproduce this failure on `main`, so I'm going to close this as resolved for now. If you happen to encounter the issue again, a small Mix project that reproduces the error will help me troubleshoot further.

**Closed by bitwalker** 2023-06-22 18:41 UTC
