### ISSUE TITLE
unable to connect to & Cannot get connection id for node

### ISSUE THREAD

**Issue by KamilLelonek** [bitwalker/libcluster#142] opened 2020-10-12 11:31 UTC
## Description

When two machines are started almost at the same time, I see the following error:

```
Oct 12 04:22:12 nccos-h1sq5z potion_proxy[507]: 04:22:12.690 [warn] [libcluster:proxy] unable to connect to :"potion_proxy@bbaab351-4eeb-a8a5-b67d-a0105f647080.local"
Oct 12 04:22:12 nccos-h1sq5z potion_proxy[507]: 04:22:12.692 [error]
Oct 12 04:22:12 nccos-h1sq5z potion_proxy[507]: ** Cannot get connection id for node :"potion_proxy@cf6b84e2-e804-3214-e237-050d5f621306.local"
```

These logs come from machine `potion_proxy@cf6b84e2-e804-3214-e237-050d5f621306.local` while the other is `potion_proxy@bbaab351-4eeb-a8a5-b67d-a0105f647080.local`.

The cluster strategy is gossip:

```elixir
config :libcluster,
  topologies: [
    proxy: [
      strategy: Cluster.Strategy.Gossip
    ]
  ]
```

## Environment

```
Erlang/OTP 22 [erts-10.7.2] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]

Elixir 1.9.4 (compiled with Erlang/OTP 22)
```

**Comment by bitwalker** [comment] 2023-06-22 18:45
This should automatically resolve itself due to the gossip heartbeat, but I'm also unclear on how to reproduce this. I'm going to close this for now, since the gossip strategy is known to work in general, but if you are still having an issue and would like me to fix it, please provide enough information so I can reproduce your setup and troubleshoot it.

**Closed by bitwalker** 2023-06-22 18:45 UTC
